services:
  mongo:
    image: mongo:7
    container_name: newsly-mongo
    restart: unless-stopped
    volumes:
      - newsly-mongo-data:/data/db
    networks:
      - back-db-network
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: newsly-backend
    image: newsly-backend:latest
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=production
      - UPLOAD_DIR=/app/uploads
    depends_on:
      mongo:
        condition: service_healthy
    volumes:
      - newsly-uploads:/app/uploads
      - ./backend/.env:/app/.env   # monta o .env como volume
    ports:
      - "3001:3001"
    restart: unless-stopped
    command: >
      sh -c "echo '>>> DATABASE_URL no backend runtime: $DATABASE_URL' &&
             npx prisma generate &&
             node dist/main.js"
    networks:
      - front-back-network
      - back-db-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: newsly-frontend
    image: newsly-frontend:latest
    env_file:
      - ./frontend/.env
    environment:
      - NODE_ENV=production
    depends_on:
      backend:
        condition: service_started
    ports:
      - "3000:3000"
    restart: unless-stopped
    command: >
      sh -c "echo '>>> NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL' &&
             node server.js"
    networks:
      - front-back-network

volumes:
  newsly-uploads:
  newsly-mongo-data:

networks:
  front-back-network:
    driver: bridge
  back-db-network:
    driver: bridge
